### PR TITLE
Allow an optional '---' as the first line in a file.

### PR DESCRIPTION
**Pull request by kuwerty**

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
Curious on why this was closed w/ no discussion?  I have this same need in my project, and found this issue from a few years back, but there is no discussion on why it was closed or not accepted?

**Comment by kylelemons** [comment]
I don't recall.  @cpjolicoeur Why does this come up for you?  Gypsy is not intended to be a full-fledged reimplementation of YAML, so I have to draw the line somewhere.

**Comment by cpjolicoeur** [comment]
I had been using hand rolled YAML parsing on past projects, but figured I'd take a look and see what is out there.

I have YAML files from various 3rd party tools and applications where the `---` is the opening specifier.  According to the [YAML spec on structures](http://www.yaml.org/spec/1.2/spec.html#id2760395), the `---` separates the actual document content from directives, and in the case of no directives (which is most common) the `---` signals the start of the document.

Since seeing directives in YAML is quite uncommon, a lot of YAML marshalling tools just omit the `---` to mark the start of content, while others through it in as the first line.

This `go-gypsy` package seems to be more inclined to work with using YAML as a pure configuration file type situation so I can see why it wouldn't support the `---` as when writing YAML config's by hand you usually wouldn't put them in.  They really mostly only show up when YAML files are dynamically generated from code and other dumpers.

**Comment by kuwerty** [comment]
As @cpjolicoeur, my own case was that the writer of the yaml file inserted ‘—‘ there.  I was using Gypsy as part of a larger flow and Gypsy suited my needs in other respects (and it's a nice, pleasant library to integrate).

I guess I thought it fit in Gypsy because it's both valid yaml syntax and it was a really simple change to make. It was ages ago but if you wanted to strip it off outside, you'd probably need to implement some io.Reader looking interface which is a much more complicated job.

**Comment by kylelemons** [comment]
Hmm, yeah the API as-is doesn't really make it easy to do your own preprocessing on files.

I'd vaguely prefer a PR that adds an io.Reader-based init that lets someone read a file, seek 3 bytes, and pass it off to gypsy but if this PR will help you guys use it, then sure, as long as it's also mentioned in the docs and tests.

**Pull request closed without merging**
